version: "3.1"

services:
  db:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=bootcamp2021
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
     
  myserver:
     build: . 
     ports:
       - 5000:5000
     links:
       - db  
     restart: always
